### ISSUE TITLE
I'm not sure on what to do

### ISSUE THREAD

**Issue by Sophia-Villamayor** [Sophia-Villamayor/horizontal-nav#1]
@thomasjbradley 
I've written my html code and my css so far. However, I'm stuck on the errors Markbot is giving me, along with how I can make the buttons move when I reduce the size of my screen. I'm not too sure if I need to change something, or if I have done something incorrect. Sorry!

![Image 2019-10-12 at 12 47 PM](https://user-images.githubusercontent.com/54897840/66704922-89378700-ecee-11e9-80bc-08131db87bfe.jpg)

![Image 2019-10-12 at 12 46 PM](https://user-images.githubusercontent.com/54897840/66704907-5ee5c980-ecee-11e9-901c-51ef61d0727b.jpg)

**Comment by thomasjbradley** [comment]
The `body` should have a margin of just `0` no `em`—0 is 0 it doesn’t need a unit.

The font family of "Bevan" should be just on the `<h1>`—the rest of the site uses Georgia.

You need to use `display: inline-block` to make the navigation items get side-by-side.

**Comment by Sophia-Villamayor** [comment]
@thomasjbradley I'm so sorry to bother you on a Thanksgiving weekend. Although, I added everything you mentioned, but it keeps saying there needs to be a different value set in h1, and my buttons don't seem to become side by side. I asked a couple of friends for help but they are also confused. So sorry!!

**Comment by thomasjbradley** [comment]
It seems you figure the buttons out—good work!

The font-family for the `<h1>`, `Bevan`, is a `serif` font not a `sans-serif` font.
